[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_contracts = "DvYFdnuamvwsxXDaHYAzfLSZ8AbDQd9BY2x71j6s87cs"

[programs.devnet]
solana_contracts = "DvYFdnuamvwsxXDaHYAzfLSZ8AbDQd9BY2x71j6s87cs"

[programs.mainnet-beta]
solana_contracts = "DvYFdnuamvwsxXDaHYAzfLSZ8AbDQd9BY2x71j6s87cs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '~/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
