[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_contracts = "EY9L3yoUv9SV8mqRm2gZz5Etb7g7Z9hkKgz5dHW9ZsNP"

[programs.devnet]
solana_contracts = "EY9L3yoUv9SV8mqRm2gZz5Etb7g7Z9hkKgz5dHW9ZsNP"

[programs.mainnet]
solana_contracts = "EY9L3yoUv9SV8mqRm2gZz5Etb7g7Z9hkKgz5dHW9ZsNP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '~/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
