[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_contracts = "7mQjTQKBv9QzW1xGyqHs4ECDzWRfWp8hMiyq1fTC3MEc"

[programs.devnet]
solana_contracts = "7mQjTQKBv9QzW1xGyqHs4ECDzWRfWp8hMiyq1fTC3MEc"

[programs.mainnet]
solana_contracts = "7mQjTQKBv9QzW1xGyqHs4ECDzWRfWp8hMiyq1fTC3MEc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '~/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
