#!/bin/bash  

# Validator command  
COMMAND="solana-test-validator -r --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s metadata.so"  

# Append any additional arguments passed to the script  
for arg in "$@"  
do  
    COMMAND+=" $arg"  
done  

# Execute the command  
eval $COMMAND
