type WrapEvent @entity {
  id: ID!
  assetInfo: AssetInfo!
  assetAccount: String!
  owner: String!
  blockNumber: BigInt!
  timestamp: BigInt!
}

type AssetInfo @entity {
  id: ID!
  name: String!
  symbol: String!
  # 其他 AssetInfo 相关字段
}

type MintEvent @entity {
  id: ID!
  assetAccount: String!
  mintAccount: String!
  tokenAccount: String!
  blockNumber: BigInt!
  timestamp: BigInt!
}

type BurnEvent @entity {
  id: ID!
  assetAccount: String!
  mintAccount: String!
  tokenAccount: String!
  blockNumber: BigInt!
  timestamp: BigInt!
}

type StakeEvent @entity {
  id: ID!
  assetAccount: String!
  stakeAccount: String!
  mintAccount: String!
  ownerAccount: String!
  authorityAccount: String!
  ownerTokenAccount: String!
  stakerTokenAccount: String!
  blockNumber: BigInt!
  timestamp: BigInt!
}

type UnstakeEvent @entity {
  id: ID!
  assetAccount: String!
  stakeAccount: String!
  mintAccount: String!
  ownerAccount: String!
  authorityAccount: String!
  ownerTokenAccount: String!
  stakerTokenAccount: String!
  blockNumber: BigInt!
  timestamp: BigInt!
}